"use client";
import { ArrowLeft, ArrowDown, ArrowUp, Plus, Copy, ExternalLink, Route, Search, Trash2, Check, Save } from "lucide-react";
import { useState } from "react";
import type { ContactRow, JourneyAsset, JourneyDraft, JourneySummary } from "./trust-app-shared";
import { AssetPreview } from "./sage-library";

export function SageJourneys({ journeys, onEdit, onNew, onResume, hasDraft, onArchive }: { journeys: JourneySummary[]; onEdit: (j: JourneySummary) => void; onNew: () => void; onResume: () => void; hasDraft: boolean; onArchive: () => void }) {
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("all");
  const rows = journeys.filter(j => j.title.toLowerCase().includes(query.toLowerCase()) && (filter === "all" || (filter === "published") === j.isPublic));
  return <><header className="sage-page-heading"><div><h1>Journeys</h1><p>Focused proof for every buyer conversation.</p></div><div className="sage-actions"><button onClick={onArchive}>Manage archive</button><button className="sage-primary" onClick={onNew}><Plus />New journey</button></div></header>{hasDraft && <button className="sage-resume" onClick={onResume}><Route /><span>Continue your current journey<small>Your work stays with this workspace.</small></span><ArrowLeft style={{ transform: "rotate(180deg)" }} /></button>}<label className="sage-search"><Search /><input aria-label="Search journeys" placeholder="Search journeys" value={query} onChange={e => setQuery(e.target.value)} /></label><div className="sage-segments">{["all", "published", "draft"].map(f => <button key={f} aria-pressed={filter === f} onClick={() => setFilter(f)}>{f === "all" ? "All journeys" : f === "draft" ? "Drafts" : "Published"}</button>)}</div><div className="sage-journey-list">{rows.map(j => <article className="sage-journey-card" key={j.id}><div className="sage-journey-cover">{j.assets[0]?.thumbnailUrl ? <img src={j.assets[0].thumbnailUrl} alt="" /> : <Route />}</div><div><span className={`sage-badge ${j.isPublic ? "is-live" : ""}`}>{j.isPublic ? "Published" : "Draft"}</span><h2>{j.title}</h2><p>{j.assets.length} assets{j.publishedAt ? ` · Published ${new Date(j.publishedAt).toLocaleDateString()}` : ""}</p><div className="sage-actions"><button onClick={() => onEdit(j)}>Edit journey</button>{j.isPublic && <a href={j.shareUrl} target="_blank" rel="noreferrer">Open live journey <ExternalLink /></a>}</div></div></article>)}</div>{!rows.length && <div className="sage-empty"><Route /><h2>{journeys.length ? "No matching journeys" : "Create a journey worth sharing"}</h2><p>{journeys.length ? "Try a different search or filter." : "Combine the videos and documents that answer your buyer's questions."}</p><button onClick={journeys.length ? () => { setQuery(""); setFilter("all"); } : onNew}>{journeys.length ? "Clear filters" : "Create your first journey"}</button></div>}</>;
}

type Recipient = { contactId?: string; name?: string; email?: string; phone?: string; company?: string; crmSource?: string; externalId?: string };
export function SageJourneyEditor({ draft, assets, onChange, onMove, onRemove, onLibrary, onBack, onSave, onGenerate, working, shareUrl, personalUrl, published, contacts, onContactShare, saved }: { draft: JourneyDraft; assets: JourneyAsset[]; onChange: (d: JourneyDraft) => void; onMove: (id: string, direction: -1 | 1) => void; onRemove: (id: string) => void; onLibrary: () => void; onBack: () => void; onSave: (publish: boolean) => void; onGenerate: () => void; working: boolean; shareUrl: string; personalUrl: string; published: boolean; contacts: ContactRow[]; onContactShare: (c: Recipient) => void; saved: boolean }) {
  const [step, setStep] = useState("content");
  const [previewIndex, setPreviewIndex] = useState(0);
  const [search, setSearch] = useState("");
  const [contactId, setContactId] = useState("");
  const [manual, setManual] = useState(false);
  const [recipient, setRecipient] = useState<Recipient>({});
  const [copyStatus, setCopyStatus] = useState("");
  const [linkRecipient, setLinkRecipient] = useState("");
  const recipientKey = manual ? JSON.stringify(recipient) : contactId;
  const found = contacts.filter(c => `${c.name} ${c.email} ${c.phone} ${c.sourceLabel}`.toLowerCase().includes(search.toLowerCase())).slice(0, 30);
  const chosen = contacts.find(c => c.id === contactId);
  const preview = assets[Math.min(previewIndex, assets.length - 1)];
  async function copy(url: string) { try { await navigator.clipboard.writeText(url); setCopyStatus("Link copied"); } catch { setCopyStatus("Could not copy. Select the link and copy it manually."); } }
  return <section className="sage-editor"><button onClick={onBack} className="sage-back"><ArrowLeft />All journeys</button><header className="sage-page-heading"><div><h1>{draft.title || "New journey"}</h1><p><span className="sage-badge">{saved ? "Saved" : "Unsaved changes"}</span> {published ? "Published journey" : "Private draft"}</p></div><button disabled={working || !assets.length || published} onClick={() => onSave(false)} title={published ? "Use Publish changes to update this live journey." : undefined}><Save />Save draft</button></header><nav className="sage-editor-tabs" aria-label="Journey steps">{["content", "details", "preview", "share"].map((s, i) => <button key={s} aria-current={step === s ? "step" : undefined} onClick={() => setStep(s)}><span>{i + 1}</span>{s[0].toUpperCase() + s.slice(1)}</button>)}</nav>
    {step === "content" && <section className="sage-editor-content"><p>Choose the order your buyer will see. Use the arrows to move an asset.</p>{assets.map((a, i) => <article className="sage-sequence-row" key={a.id}><span className="sage-sequence-number">{i + 1}</span><div className="sage-thumbnail">{a.thumbnailUrl ? <img src={a.thumbnailUrl} alt="" /> : <Route />}</div><div><strong>{a.title}</strong><small>{a.assetType === "video" ? "Video" : "Document / embed"}</small></div><div className="sage-order-actions"><button disabled={working || !i} aria-label={`Move ${a.title} up`} onClick={() => onMove(a.id, -1)}><ArrowUp /></button><button disabled={working || i === assets.length - 1} aria-label={`Move ${a.title} down`} onClick={() => onMove(a.id, 1)}><ArrowDown /></button><button disabled={working} aria-label={`Remove ${a.title}`} onClick={() => onRemove(a.id)}><Trash2 /></button></div></article>)}{!assets.length && <div className="sage-empty"><Route /><h2>Start with the buyer's question</h2><p>Choose proof that helps answer it: a project video, testimonial, proposal, or explanation.</p></div>}<button className="sage-add-row" onClick={onLibrary}><Plus />Choose content from library</button></section>}
    {step === "details" && <section className="sage-panel sage-form"><label>Internal name<input value={draft.title} onChange={e => onChange({ ...draft, title: e.target.value })} placeholder="Roofing - pricing objections" /></label><label>Buyer-facing headline<input value={draft.heading} onChange={e => onChange({ ...draft, heading: e.target.value })} placeholder="A closer look at your roofing project" /></label><label>Introduction<textarea value={draft.description} onChange={e => onChange({ ...draft, description: e.target.value })} placeholder="What will these examples help your buyer understand?" /></label><div className="sage-form-columns"><label>Next-action button text<input value={draft.ctaLabel} onChange={e => onChange({ ...draft, ctaLabel: e.target.value })} /></label><label>Button destination<input type="url" value={draft.ctaUrl} onChange={e => onChange({ ...draft, ctaUrl: e.target.value })} placeholder="https://yourcompany.com/book" /></label></div><details><summary>Organization and writing assistance</summary><label>Folder<input value={draft.folderName} onChange={e => onChange({ ...draft, folderName: e.target.value })} /></label><p>Writing assistance can change the headline, introduction, and asset order. Review the result before publishing.</p><button disabled={working || !assets.some(a => a.videoId)} onClick={onGenerate}>Suggest copy and order</button></details></section>}
    {step === "preview" && <section className="sage-buyer-preview"><span className="sage-badge">Preview - no activity recorded</span><h2>{draft.heading || draft.title || "Your journey"}</h2><p>{draft.description}</p>{preview ? <><AssetPreview key={preview.id} asset={preview} /><h3>{preview.title}</h3><div className="sage-actions"><button disabled={!previewIndex} onClick={() => setPreviewIndex(i => i - 1)}>Previous</button><span>{Math.min(previewIndex + 1, assets.length)} of {assets.length}</span><button disabled={previewIndex >= assets.length - 1} onClick={() => setPreviewIndex(i => i + 1)}>Next</button></div></> : <p>Add content to preview your journey.</p>}{draft.ctaUrl && <a className="sage-primary" href={draft.ctaUrl} target="_blank" rel="noreferrer">{draft.ctaLabel || "Continue"}<ExternalLink /></a>}</section>}
    {step === "share" && <section className="sage-panel sage-form"><h2>Share with a buyer</h2>{!published || !saved ? <p>{published ? "Publish your changes before sharing the updated journey." : "Publish this journey to create its shareable link."}</p> : <><label>General journey link<input value={shareUrl} readOnly onFocus={e => e.target.select()} /></label><button onClick={() => copy(shareUrl)}><Copy />Copy general link</button><hr /><h3>Create a personalized link</h3><p>Associate engagement with a recipient. This creates a link; it does not send a message.</p><div className="sage-segments"><button aria-pressed={!manual} onClick={() => setManual(false)}>Choose CRM contact</button><button aria-pressed={manual} onClick={() => setManual(true)}>Enter recipient</button></div>{manual ? <div className="sage-form-columns"><label>Name<input value={recipient.name || ""} onChange={e => setRecipient({ ...recipient, name: e.target.value })} /></label><label>Email<input type="email" value={recipient.email || ""} onChange={e => setRecipient({ ...recipient, email: e.target.value })} /></label><label>Phone<input type="tel" value={recipient.phone || ""} onChange={e => setRecipient({ ...recipient, phone: e.target.value })} /></label></div> : <><label className="sage-search"><Search /><input aria-label="Find recipient" placeholder="Search name, email, phone, or CRM" value={search} onChange={e => setSearch(e.target.value)} /></label><div className="sage-recipient-list">{found.map(c => <button key={c.id} aria-pressed={contactId === c.id} onClick={() => setContactId(c.id)}><span><strong>{c.name || c.email || c.phone || "Unnamed contact"}</strong><small>{[c.sourceLabel, c.detailLabel, c.email].filter(Boolean).join(" · ")}</small></span>{contactId === c.id && <Check />}</button>)}{!found.length && <p>No matching contacts. Enter a recipient or connect your CRM in Settings.</p>}</div></>}<button disabled={working || (manual ? !recipient.name && !recipient.email && !recipient.phone : !chosen)} onClick={() => { setLinkRecipient(recipientKey); onContactShare(manual ? recipient : chosen?.contactRecordId ? { contactId: chosen.contactRecordId } : { name: chosen?.name || undefined, email: chosen?.email || undefined, phone: chosen?.phone || undefined, company: chosen?.company || undefined, crmSource: chosen?.crmSource || undefined, externalId: chosen?.externalId || undefined }); }}>Create personalized link</button>{personalUrl && !working && linkRecipient === recipientKey && <><label>Personalized link<input value={personalUrl} readOnly onFocus={e => e.target.select()} /></label><button onClick={() => copy(personalUrl)}><Copy />Copy personalized link</button></>}</>}<p role="status">{copyStatus}</p></section>}
    <footer className="sage-editor-footer"><span>{assets.length} assets</span><div className="sage-actions"><button onClick={() => setStep("preview")}>Preview</button><button className="sage-primary" disabled={working || !assets.length || !draft.title.trim()} onClick={() => { onSave(true); setStep("share"); }}>{working ? "Saving..." : published ? "Publish changes" : "Publish journey"}</button></div></footer>
  </section>;
}
