"use client";

import { ArrowLeft, ArrowRight, FileText, Grid2X2, List, Plus, Search, Video, X, ExternalLink, Archive } from "lucide-react";
import { useEffect, useState, useDeferredValue } from "react";
import { buildJourneyAssetFromVideo, formatDuration, type DbVideo, type LibraryAssetRow, type JourneyAsset, type JourneyEmbedDraft, type VideoContext, buildOptions } from "./trust-app-shared";
import { ContextEditor } from "./trust-app-library-ui";

export function libraryItem(asset: LibraryAssetRow): JourneyAsset { return { ...asset, libraryAssetId: asset.id, videoId: null, durationSeconds: null, position: 1, note: null }; }
export function AssetPreview({ asset }: { asset: JourneyAsset }) {
  const [playing, setPlaying] = useState(false);
  if (!asset.embedUrl) return <div className="sage-preview-placeholder"><FileText /><p>Embedded preview unavailable.</p>{asset.sourceUrl && <a href={asset.sourceUrl} target="_blank" rel="noreferrer">Open original <ExternalLink /></a>}</div>;
  if (!playing) return <button className={`sage-media-poster ${asset.assetType !== "video" ? "is-document" : ""}`} onClick={() => setPlaying(true)} aria-label={`Preview ${asset.title}`}>{asset.thumbnailUrl ? <img src={asset.thumbnailUrl} alt="" /> : <FileText />}<span>{asset.assetType === "video" ? "Play video" : "View document"}</span></button>;
  const directVideo = asset.assetType === "video" && /\.(mp4|webm|mov)(\?|$)/i.test(asset.embedUrl);
  return directVideo ? <video className="sage-media-video" src={asset.embedUrl} controls playsInline autoPlay /> : <iframe className={`sage-media-frame ${asset.assetType !== "video" ? "is-document" : ""}`} src={asset.embedUrl} title={asset.title} allow="autoplay; encrypted-media; picture-in-picture; fullscreen" allowFullScreen />;
}

export function SageLibrary({ videos, libraryAssets, assetDraft, onAssetDraftChange, onSaveAsset, saving, onArchive, onDeleteAsset, onSaveContext, onImport, onAddItems, draftCount, onOpenDraft }: { videos: DbVideo[]; libraryAssets: LibraryAssetRow[]; assetDraft: JourneyEmbedDraft; onAssetDraftChange: (draft: JourneyEmbedDraft) => void; onSaveAsset: () => void; saving: boolean; onArchive: (v: DbVideo) => void; onDeleteAsset: (a: LibraryAssetRow) => void; onSaveContext: (v: DbVideo, c: VideoContext) => void; onImport: () => void; onAddItems: (items: JourneyAsset[]) => void; draftCount: number; onOpenDraft: () => void }) {
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("all");
  const [layout, setLayout] = useState("list");
  const [selectedIds, setSelectedIds] = useState<string[]>([]);
  const [previewId, setPreviewId] = useState<string | null>(null);
  const [adding, setAdding] = useState(false);
  const deferredQuery = useDeferredValue(query.toLowerCase());
  useEffect(() => { if (previewId && window.matchMedia("(max-width: 760px)").matches) document.getElementById("sage-content")?.scrollTo(0, 0); }, [previewId]);
  const videoById = new Map(videos.map(v => [v.id, v]));
  const items = [...videos.map(v => buildJourneyAssetFromVideo(v)), ...libraryAssets.map(libraryItem)];
  const key = (a: JourneyAsset) => `${a.videoId ? "v" : "a"}:${a.videoId || a.libraryAssetId}`;
  const visible = items.filter(a => (filter === "all" || (filter === "video" ? a.assetType === "video" : a.assetType !== "video")) && `${a.title} ${a.summary || ""} ${a.sourcePlatform} ${JSON.stringify(a.metadata?.customContext || {})} ${videoById.get(a.videoId)?.tags?.join(" ") || ""}`.toLowerCase().includes(deferredQuery));
  const selected = items.filter(a => selectedIds.includes(key(a)));
  const preview = items.find(a => key(a) === previewId);
  const originalVideo = videos.find(v => v.id === preview?.videoId);
  const originalAsset = libraryAssets.find(a => a.id === preview?.libraryAssetId);
  function toggle(id: string) { setSelectedIds(ids => ids.includes(id) ? ids.filter(v => v !== id) : [...ids, id]); }
  return <section className={`sage-library ${preview ? "has-preview" : ""}`}>
    <div className="sage-library-main"><header className="sage-page-heading"><div><h1>Library</h1><p>The right proof. Ready to share.</p></div><button className="sage-primary" onClick={() => setAdding(true)}><Plus />Add content</button></header>
      {adding && <section className="sage-panel sage-add-content" aria-label="Add content"><div className="sage-section-heading"><h2>Add to your library</h2><button onClick={() => setAdding(false)} aria-label="Close add content"><X /></button></div><p>Save a cloud-hosted document or embed, or import videos from a channel or folder.</p><form onSubmit={e => { e.preventDefault(); onSaveAsset(); }}><label>Title<input value={assetDraft.title} onChange={e => onAssetDraftChange({ ...assetDraft, title: e.target.value })} placeholder="e.g. Financing explained" /></label><label>Document link or embed code<input required value={assetDraft.url} onChange={e => onAssetDraftChange({ ...assetDraft, url: e.target.value })} placeholder="Google Doc, Drive file, PDF, Gamma, or iframe" /></label><small>Files stay with their host. Make sure recipients have permission to view them.</small><div className="sage-actions"><button className="sage-primary" disabled={saving || !assetDraft.url.trim()}>Save asset</button><button type="button" onClick={onImport}>Import a video, channel, or folder <ArrowRight /></button></div></form></section>}
      <label className="sage-search"><Search /><input aria-label="Search library" placeholder="Search content, topics, or objections" value={query} onChange={e => setQuery(e.target.value)} />{query && <button onClick={() => setQuery("")} aria-label="Clear search"><X /></button>}</label>
      <div className="sage-library-toolbar"><div className="sage-segments" aria-label="Content type">{[["all", "All content"], ["video", "Videos"], ["document", "Documents"]].map(([id, label]) => <button key={id} aria-pressed={filter === id} onClick={() => setFilter(id)}>{label}</button>)}</div><div className="sage-view-switch"><button aria-label="List view" aria-pressed={layout === "list"} onClick={() => setLayout("list")}><List /></button><button aria-label="Grid view" aria-pressed={layout === "grid"} onClick={() => setLayout("grid")}><Grid2X2 /></button></div></div>
      {!items.length ? <div className="sage-empty"><FileText /><h2>Your first piece of proof starts here</h2><p>Add a video, proposal, or presentation, then share a focused journey with a buyer.</p><button className="sage-primary" onClick={() => setAdding(true)}><Plus />Add your first content</button></div> : !visible.length ? <div className="sage-empty"><Search /><h2>No matching content</h2><p>Try another phrase or clear your filters.</p><button onClick={() => { setQuery(""); setFilter("all"); }}>Clear search and filters</button></div> : <div className={`sage-content-items is-${layout}`}>{visible.map(a => <article key={key(a)} className={`sage-content-item ${selectedIds.includes(key(a)) ? "is-selected" : ""} ${previewId === key(a) ? "is-previewed" : ""}`}><input type="checkbox" aria-label={`Select ${a.title}`} checked={selectedIds.includes(key(a))} onChange={() => toggle(key(a))} /><button className="sage-item-open" onClick={() => setPreviewId(key(a))}><span className="sage-thumbnail">{a.thumbnailUrl ? <img src={a.thumbnailUrl} loading="lazy" alt="" /> : <FileText />}</span><span className="sage-item-copy"><strong>{a.title}</strong><small>{a.assetType === "video" ? <Video /> : <FileText />}{a.assetType === "video" ? "Video" : "Document"}{a.durationSeconds ? ` · ${formatDuration(a.durationSeconds)}` : ""}<span className="sage-item-provider"> · {a.sourcePlatform.replace(/_/g, " ")}</span></small></span><ArrowRight className="sage-row-arrow" /></button></article>)}</div>}
      <footer className="sage-selection-bar"><span>{selected.length ? `${selected.length} selected` : `${visible.length} ${visible.length === 1 ? "item" : "items"}`}</span>{selected.length ? <div className="sage-actions"><button onClick={() => setSelectedIds([])}>Clear</button><button className="sage-primary" onClick={() => { onAddItems(selected); setSelectedIds([]); }}>{draftCount ? "Add to journey" : "Create journey"}<ArrowRight /></button></div> : draftCount > 0 ? <button onClick={onOpenDraft}>Continue journey ({draftCount})<ArrowRight /></button> : null}</footer>
    </div>
    {preview && <aside className="sage-asset-preview"><button className="sage-preview-back" onClick={() => setPreviewId(null)}><ArrowLeft />Back to library</button><AssetPreview key={key(preview)} asset={preview} /><h2>{preview.title}</h2><span className="sage-badge">{preview.assetType === "video" ? "Video" : "Document"}</span><p>{preview.summary || "Add this asset to a journey to share it with a buyer."}</p><button className="sage-primary" onClick={() => onAddItems([preview])}><Plus />Add to journey</button>{preview.sourceUrl && <a className="sage-original-link" href={preview.sourceUrl} target="_blank" rel="noreferrer">Open original <ExternalLink /></a>}{originalVideo && <details><summary>Edit searchable context</summary><ContextEditor key={originalVideo.id} video={originalVideo} saving={saving} options={buildOptions(videos, [])} onSave={onSaveContext} /></details>}<button className="sage-danger" onClick={() => { if (originalVideo) onArchive(originalVideo); else if (originalAsset) onDeleteAsset(originalAsset); }}><Archive />Archive asset</button><p className="sage-help">Recipient access is controlled by the original file host.</p></aside>}
  </section>;
}
