"use client";
import { ArrowRight, Check, FileText, Plus, Route, Search } from "lucide-react";
import { useState } from "react";
import type { ContactRow, JourneySummary, MetricsState } from "./trust-app-shared";
import type { SageView } from "./sage-shell";

export function SageHome({ contentCount, journeys, metrics, onNavigate, onNew, onEdit, draftCount }: { contentCount: number; journeys: JourneySummary[]; metrics: MetricsState; onNavigate: (v: SageView) => void; onNew: () => void; onEdit: (j: JourneySummary) => void; draftCount: number }) {
  const published = journeys.filter(j => j.isPublic);
  return <><header className="sage-page-heading"><div><span className="sage-eyebrow">Your workspace</span><h1>Make the next conversation count.</h1><p>Find the proof. Share the story. See what connects.</p></div><button className="sage-primary" onClick={onNew}><Plus />New journey</button></header><section className="sage-home-hero"><div><span className="sage-eyebrow">{draftCount ? "Pick up where you left off" : contentCount ? "Ready for your next buyer" : "Start with what you already have"}</span><h2>{draftCount ? "Your journey is taking shape." : contentCount ? "Your best work can do the talking." : "Turn real work into useful proof."}</h2><p>{draftCount ? `${draftCount} assets are waiting in your current journey.` : "Bring together videos, project examples, and documents that answer a buyer's questions."}</p><button className="sage-primary" onClick={() => onNavigate(draftCount ? "editor" : "library")}>{draftCount ? "Continue journey" : "Open library"}<ArrowRight /></button></div><div className="sage-home-mark"><Route /><span>Proof that moves<br />the conversation forward.</span></div></section><section className="sage-setup-grid">{[{ label: "Add your content", done: contentCount > 0, text: `${contentCount} assets in your library`, view: "library" }, { label: "Create a journey", done: journeys.length > 0, text: `${journeys.length} saved journeys`, view: "journeys" }, { label: "Share and learn", done: metrics.views.length > 0, text: `${published.length} published journeys`, view: "metrics" }].map((s, i) => <button key={s.label} onClick={() => onNavigate(s.view as SageView)}><span className="sage-step-circle">{s.done ? <Check /> : i + 1}</span><span><strong>{s.label}</strong><small>{s.text}</small></span><ArrowRight /></button>)}</section><div className="sage-section-heading"><h2>Recent journeys</h2><button onClick={() => onNavigate("journeys")}>View all<ArrowRight /></button></div>{journeys.length ? <div className="sage-home-recents">{journeys.slice(0, 4).map(j => <button key={j.id} onClick={() => onEdit(j)}><Route /><span><strong>{j.title}</strong><small>{j.assets.length} assets · {j.isPublic ? "Published" : "Draft"}</small></span><ArrowRight /></button>)}</div> : <div className="sage-panel"><p>Your saved journeys will appear here. Start with a specific buyer question and choose a few assets that answer it.</p></div>}</>;
}

export function SageRecipients({ contacts, metrics, journeys }: { contacts: ContactRow[]; metrics: MetricsState; journeys: JourneySummary[] }) {
  const [search, setSearch] = useState("");
  const [selected, setSelected] = useState<string | null>(null);
  const contact = contacts.find(c => c.id === selected);
  const events = contact ? metrics.views.filter(e => e.metadata?.contactId && [contact.id, contact.contactRecordId].includes(e.metadata.contactId)) : [];
  return <section className="sage-panel"><div className="sage-section-heading"><h2>Recipients & CRM context</h2><span>{contacts.length} records</span></div><p>Journey engagement and linked CRM information. A sold date is a CRM outcome, not proof that a journey caused the sale.</p><label className="sage-search"><Search /><input aria-label="Search recipients" placeholder="Search people or CRM source" value={search} onChange={e => setSearch(e.target.value)} /></label><div className="sage-recipient-list">{contacts.filter(c => `${c.name} ${c.email} ${c.sourceLabel}`.toLowerCase().includes(search.toLowerCase())).slice(0, 30).map(c => <button key={c.id} onClick={() => setSelected(c.id)} aria-pressed={selected === c.id}><span><strong>{c.name || c.email || "Unnamed contact"}</strong><small>{[c.sourceLabel, c.detailLabel, c.status].filter(Boolean).join(" · ") || "Recipient"}</small></span><ArrowRight /></button>)}</div>{contact && <section className="sage-recipient-detail"><h3>{contact.name || contact.email}</h3><p>{[contact.email, contact.phone].filter(Boolean).join(" · ")}</p><p>CRM sold date: {contact.soldDate || "Not supplied"}</p><h4>Journey timeline</h4>{events.length ? events.map(e => <div key={e.id}><strong>{journeys.find(j => j.id === e.journey_id)?.title || "Journey"}</strong><p>{e.event_type.replace(/_/g, " ")} · {e.created_at ? new Date(e.created_at).toLocaleString() : "Date unavailable"}</p></div>) : <p>No directly linked journey events found for this record.</p>}</section>}{!contacts.length && <div className="sage-empty"><FileText /><p>Recipients appear after you create personalized links or load CRM contacts.</p></div>}</section>;
}
